# Site settings
title: E Posta Aç - E Posta Kur ve Kaydol
description: "E Posta Aç ve E Posta Kur"
url: "https://www.epostakaydol.site"
author:
  name: "E Posta Uzmanı"
  url: "https://www.epostakaydol.site"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
